# Generated by Django 3.2 on 2022-07-20 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_entry_working_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='Day',
            new_name='day',
        ),
    ]
