# Generated by Django 4.0.6 on 2022-08-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_rename_day_entry_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='note',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='entry',
            name='working_hours',
            field=models.FloatField(choices=[(1.0, '1 Day'), (0.5, '0.5 Day'), (1.5, '1.5 Day')], default=None),
        ),
    ]
